// Quick-start templates for popular alliance strategy games.
// Pick one, edit alliance name + server offset, done.

const mkId = (prefix, i) => `${prefix}_${i}`;

export const TEMPLATES = [
  {
    id: "rok",
    label: "Rise of Kingdoms",
    emoji: "🏰",
    accent: "#2563EB",
    description: "MGE, Ark of Osiris, KvK",
    schedule: {
      name: "My Kingdom",
      offset: "+00:00",
      events: [
        {
          id: mkId("rok", 1),
          name: "Lvl 5 Barbarian",
          category: "Combat",
          anchor: "08:00",
          interval: 240,
          duration: 0,
          lead: 5,
        },
        {
          id: mkId("rok", 2),
          name: "Mightiest Governor",
          category: "Combat",
          anchor: "00:00",
          interval: 1440,
          duration: 60,
          lead: 15,
        },
        {
          id: mkId("rok", 3),
          name: "Ark of Osiris",
          category: "Combat",
          anchor: "20:00",
          interval: 1440,
          duration: 60,
          lead: 30,
        },
        {
          id: mkId("rok", 4),
          name: "Resource Reset",
          category: "Economy",
          anchor: "00:00",
          interval: 1440,
          duration: 0,
          lead: 5,
        },
      ],
    },
  },
  {
    id: "lords",
    label: "Lords Mobile",
    emoji: "⚔️",
    accent: "#EF4444",
    description: "Hell Event, Wonder, Lab",
    schedule: {
      name: "My Guild",
      offset: "+00:00",
      events: [
        {
          id: mkId("lm", 1),
          name: "Hell Event",
          category: "Combat",
          anchor: "13:00",
          interval: 240,
          duration: 30,
          lead: 10,
        },
        {
          id: mkId("lm", 2),
          name: "Wonder War",
          category: "Combat",
          anchor: "20:00",
          interval: 1440,
          duration: 90,
          lead: 30,
        },
        {
          id: mkId("lm", 3),
          name: "Lab Boost",
          category: "Economy",
          anchor: "12:00",
          interval: 720,
          duration: 0,
          lead: 5,
        },
        {
          id: mkId("lm", 4),
          name: "Shield Refresh",
          category: "Defense",
          anchor: "06:00",
          interval: 1440,
          duration: 0,
          lead: 30,
        },
      ],
    },
  },
  {
    id: "wos",
    label: "Whiteout Survival",
    emoji: "❄️",
    accent: "#0EA5E9",
    description: "Bear, SvS, Alliance Mobi",
    schedule: {
      name: "My State",
      offset: "+00:00",
      events: [
        {
          id: mkId("wos", 1),
          name: "Bear Trap",
          category: "Combat",
          anchor: "12:00",
          interval: 1440,
          duration: 30,
          lead: 15,
        },
        {
          id: mkId("wos", 2),
          name: "SvS Phase",
          category: "Combat",
          anchor: "00:00",
          interval: 1440,
          duration: 240,
          lead: 30,
        },
        {
          id: mkId("wos", 3),
          name: "Alliance Mobi",
          category: "Economy",
          anchor: "06:00",
          interval: 360,
          duration: 0,
          lead: 5,
        },
        {
          id: mkId("wos", 4),
          name: "Shield Expiry",
          category: "Defense",
          anchor: "20:00",
          interval: 1440,
          duration: 0,
          lead: 60,
        },
      ],
    },
  },
  {
    id: "sos",
    label: "State of Survival",
    emoji: "🧟",
    accent: "#16A34A",
    description: "Influencer, Plasma, Capital Clash",
    schedule: {
      name: "My State",
      offset: "+00:00",
      events: [
        {
          id: mkId("sos", 1),
          name: "Influencer Boss",
          category: "Combat",
          anchor: "16:00",
          interval: 720,
          duration: 30,
          lead: 10,
        },
        {
          id: mkId("sos", 2),
          name: "Plasma Energy",
          category: "Economy",
          anchor: "08:00",
          interval: 480,
          duration: 0,
          lead: 5,
        },
        {
          id: mkId("sos", 3),
          name: "Capital Clash",
          category: "Combat",
          anchor: "19:00",
          interval: 1440,
          duration: 90,
          lead: 30,
        },
        {
          id: mkId("sos", 4),
          name: "Settlement Shield",
          category: "Defense",
          anchor: "00:00",
          interval: 1440,
          duration: 0,
          lead: 60,
        },
      ],
    },
  },
  {
    id: "lw",
    label: "Last War: Survival",
    emoji: "🚀",
    accent: "#F97316",
    description: "Doom, Castle Battle, Crazy",
    schedule: {
      name: "My Alliance",
      offset: "+00:00",
      events: [
        {
          id: mkId("lw", 1),
          name: "Doom Apocalypse",
          category: "Combat",
          anchor: "18:00",
          interval: 1440,
          duration: 60,
          lead: 15,
        },
        {
          id: mkId("lw", 2),
          name: "Castle Battle",
          category: "Combat",
          anchor: "20:00",
          interval: 1440,
          duration: 30,
          lead: 10,
        },
        {
          id: mkId("lw", 3),
          name: "Crazy Wednesday",
          category: "Economy",
          anchor: "00:00",
          interval: 10080,
          duration: 1440,
          lead: 60,
        },
        {
          id: mkId("lw", 4),
          name: "Hero Recruit",
          category: "Economy",
          anchor: "12:00",
          interval: 720,
          duration: 0,
          lead: 5,
        },
      ],
    },
  },
  {
    id: "tw",
    label: "Top War",
    emoji: "🏝️",
    accent: "#0891B2",
    description: "Server War, Cross-Server",
    schedule: {
      name: "My Alliance",
      offset: "+00:00",
      events: [
        {
          id: mkId("tw", 1),
          name: "Server vs Server",
          category: "Combat",
          anchor: "14:00",
          interval: 1440,
          duration: 180,
          lead: 30,
        },
        {
          id: mkId("tw", 2),
          name: "Mecha Boss",
          category: "Combat",
          anchor: "10:00",
          interval: 360,
          duration: 30,
          lead: 10,
        },
        {
          id: mkId("tw", 3),
          name: "Resource Boost",
          category: "Economy",
          anchor: "08:00",
          interval: 480,
          duration: 0,
          lead: 5,
        },
      ],
    },
  },
  {
    id: "evony",
    label: "Evony",
    emoji: "👑",
    accent: "#9333EA",
    description: "Server War, Boss, Pass",
    schedule: {
      name: "My Alliance",
      offset: "+00:00",
      events: [
        {
          id: mkId("ev", 1),
          name: "Server War",
          category: "Combat",
          anchor: "20:00",
          interval: 10080,
          duration: 120,
          lead: 60,
        },
        {
          id: mkId("ev", 2),
          name: "World Boss",
          category: "Combat",
          anchor: "13:00",
          interval: 360,
          duration: 30,
          lead: 10,
        },
        {
          id: mkId("ev", 3),
          name: "Alliance War",
          category: "Combat",
          anchor: "19:00",
          interval: 1440,
          duration: 60,
          lead: 15,
        },
        {
          id: mkId("ev", 4),
          name: "Bless of Goddess",
          category: "Economy",
          anchor: "00:00",
          interval: 1440,
          duration: 0,
          lead: 5,
        },
      ],
    },
  },
  {
    id: "cod",
    label: "Call of Dragons",
    emoji: "🐉",
    accent: "#DC2626",
    description: "Darkling, Sunset, MoC",
    schedule: {
      name: "My Alliance",
      offset: "+00:00",
      events: [
        {
          id: mkId("cod", 1),
          name: "Darkling Invasion",
          category: "Combat",
          anchor: "12:00",
          interval: 360,
          duration: 30,
          lead: 10,
        },
        {
          id: mkId("cod", 2),
          name: "Sunset Canyon",
          category: "Combat",
          anchor: "18:00",
          interval: 1440,
          duration: 60,
          lead: 15,
        },
        {
          id: mkId("cod", 3),
          name: "Merlin Trials",
          category: "Combat",
          anchor: "20:00",
          interval: 1440,
          duration: 60,
          lead: 15,
        },
        {
          id: mkId("cod", 4),
          name: "Resource Reset",
          category: "Economy",
          anchor: "00:00",
          interval: 1440,
          duration: 0,
          lead: 5,
        },
      ],
    },
  },
  {
    id: "mafia",
    label: "Mafia City",
    emoji: "🏙️",
    accent: "#1F2937",
    description: "Family War, Turf, Crew",
    schedule: {
      name: "My Family",
      offset: "+00:00",
      events: [
        {
          id: mkId("mc", 1),
          name: "Family War",
          category: "Combat",
          anchor: "20:00",
          interval: 1440,
          duration: 60,
          lead: 30,
        },
        {
          id: mkId("mc", 2),
          name: "Turf War",
          category: "Combat",
          anchor: "14:00",
          interval: 480,
          duration: 30,
          lead: 10,
        },
        {
          id: mkId("mc", 3),
          name: "Crew Recruit",
          category: "Economy",
          anchor: "00:00",
          interval: 1440,
          duration: 0,
          lead: 5,
        },
      ],
    },
  },
  {
    id: "ps",
    label: "Puzzles & Survival",
    emoji: "🧩",
    accent: "#84CC16",
    description: "Doom, SvS, Hero Drop",
    schedule: {
      name: "My Alliance",
      offset: "+00:00",
      events: [
        {
          id: mkId("ps", 1),
          name: "Doom of Star",
          category: "Combat",
          anchor: "14:00",
          interval: 720,
          duration: 30,
          lead: 10,
        },
        {
          id: mkId("ps", 2),
          name: "SvS Day",
          category: "Combat",
          anchor: "00:00",
          interval: 1440,
          duration: 240,
          lead: 30,
        },
        {
          id: mkId("ps", 3),
          name: "Hero Drop",
          category: "Economy",
          anchor: "12:00",
          interval: 720,
          duration: 0,
          lead: 5,
        },
      ],
    },
  },
  {
    id: "coc",
    label: "Clash of Clans",
    emoji: "⚡",
    accent: "#FBBF24",
    description: "War, CWL, Raid Weekend",
    schedule: {
      name: "My Clan",
      offset: "+00:00",
      events: [
        {
          id: mkId("coc", 1),
          name: "Clan War Search",
          category: "Combat",
          anchor: "20:00",
          interval: 2880,
          duration: 60,
          lead: 30,
        },
        {
          id: mkId("coc", 2),
          name: "CWL Battle Day",
          category: "Combat",
          anchor: "14:00",
          interval: 1440,
          duration: 60,
          lead: 15,
        },
        {
          id: mkId("coc", 3),
          name: "Raid Weekend",
          category: "Combat",
          anchor: "00:00",
          interval: 10080,
          duration: 4320,
          lead: 60,
        },
      ],
    },
  },
  {
    id: "blank",
    label: "Start from scratch",
    emoji: "✨",
    accent: "#6B7280",
    description: "Build your own",
    schedule: { name: "", offset: "+00:00", events: [] },
  },
];
